### ISSUE TITLE
Multiple issues and doesn't run or install correctly

### ISSUE THREAD

**Issue by raw937** [Wu-Microbiology/DeepPL#1]
##  First issue curl command doesn't download the database correctly. 
```
curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=${fileid}" > /dev/null
curl -Lb ./cookie "https://drive.google.com/uc?export=download&confirm=`awk '/download/ {print $NF}' ./cookie`&id=${fileid}" -o ${filename}
tar -xvf deeppl_ckpt-340000.tar
```

## Error - header isn't correct. It's the html header
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2436  100  2436    0     0   4901      0 --:--:-- --:--:-- --:--:--  4901
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

## You have download directly from the google drive as curl and wget isn't working otherwise this. 
```
more deeppl_ckpt-340000.tar 
<!DOCTYPE html><html><head><title>Google Drive - Virus scan warning</title><meta
 http-equiv="content-type" content="text/html; charset=utf-8"/><style nonce="H3C
b1By3hQzkOxlOM9diog">.goog-link-button{position:relative;color:#15c;text-decorat
ion:underline;cursor:pointer}.goog-link-button-disabled{color:#ccc;text-decorati
```

## Tar works from google drive download
```
tar -xvf deeppl_ckpt-340000.tar 
deeppl_ckpt-340000/
deeppl_ckpt-340000/optimizer.pt
deeppl_ckpt-340000/tokenizer_config.json
deeppl_ckpt-340000/config.json
deeppl_ckpt-340000/vocab.txt
deeppl_ckpt-340000/special_tokens_map.json
deeppl_ckpt-340000/pytorch_model.bin
deeppl_ckpt-340000/training_args.bin
deeppl_ckpt-340000/scheduler.pt
```

## Post installing DNAbert multiple libraries aren't not installed correctly
```
python predict_lyso_vs_lytic.py --model_path deeppl_ckpt-340000 --fasta_file phix174.fna 
Traceback (most recent call last):
  File "predict_lyso_vs_lytic.py", line 3, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

## Install numpy from pip
```
pip install numpy
Collecting numpy
  Downloading numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8 MB)
     |████████████████████████████████| 14.8 MB 1.8 MB/s 
```

## Input as a multiple line fasta doesn't work must convert to single line fasta
```
 python predict_lyso_vs_lytic.py --model_path deeppl_ckpt-340000 --fasta_file phix174.fna 
Error: expecting fasta file to contain 2 lines where the second line is the dna sequence.
```

## Convert to single line fasta from multiline
```
awk '/^>/ {printf("\n%s\n",$0);next; } { printf("%s",$0);}  END {printf("\n");}' < phix174.fna > phix174_sl.fna
```

## Remove empty first line with sed
```
sed '/^[[:space:]]*$/d' phix174_sl.fna
```

## Torch not found - another library missing
```
python predict_lyso_vs_lytic.py --model_path deeppl_ckpt-340000 --fasta_file phix174_sl.fna 
Creating tmp directory: ./phix174_sl.fna.tmp

python ./run_finetune.py --model_type dna --tokenizer_name=dna6 --model_name_or_path deeppl_ckpt-340000 --task_name dnaprom --do_predict --data_dir ./phix174_sl.fna.tmp --max_seq_length 100 --per_gpu_pred_batch_size=32 --output_dir deeppl_ckpt-340000 --predict_dir ./phix174_sl.fna.tmp --n_process 48
Traceback (most recent call last):
  File "./run_finetune.py", line 32, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "predict_lyso_vs_lytic.py", line 71, in <module>
    r = np.load(tmp_dir + "/pred_results.npy")
  File "/home//anaconda3/envs/dnabert/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './phix174_sl.fna.tmp/pred_results.npy'
```
## install torch from pip 
```
pip install torch
Collecting torch
  Downloading torch-1.10.2-cp36-cp36m-manylinux1_x86_64.whl (881.9 MB)
     |████████████████████████████████| 881.9 MB 57 kB/s 
Collecting dataclasses
  Downloading dataclasses-0.8-py3-none-any.whl (19 kB)
Collecting typing-extensions
  Downloading typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Installing collected packages: typing-extensions, dataclasses, torch
Successfully installed dataclasses-0.8 torch-1.10.2 typing-extensions-4.1.1
```

## missing tqdm library
```python predict_lyso_vs_lytic.py --model_path deeppl_ckpt-340000 --fasta_file phix174_sl.fna 
Creating tmp directory: ./phix174_sl.fna.tmp

python ./run_finetune.py --model_type dna --tokenizer_name=dna6 --model_name_or_path deeppl_ckpt-340000 --task_name dnaprom --do_predict --data_dir ./phix174_sl.fna.tmp --max_seq_length 100 --per_gpu_pred_batch_size=32 --output_dir deeppl_ckpt-340000 --predict_dir ./phix174_sl.fna.tmp --n_process 48
Traceback (most recent call last):
  File "./run_finetune.py", line 35, in <module>
    from tqdm import tqdm, trange
ModuleNotFoundError: No module named 'tqdm'
Traceback (most recent call last):
  File "predict_lyso_vs_lytic.py", line 71, in <module>
    r = np.load(tmp_dir + "/pred_results.npy")
  File "/home//anaconda3/envs/dnabert/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './phix174_sl.fna.tmp/pred_results.npy'
```

## install tqdm with pip
```
pip install tqdm
Collecting tqdm
  Downloading tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 1.2 MB/s 
Collecting importlib-resources
  Downloading importlib_resources-5.4.0-py3-none-any.whl (28 kB)
Collecting zipp>=3.1.0
  Downloading zipp-3.6.0-py3-none-any.whl (5.3 kB)
Installing collected packages: zipp, importlib-resources, tqdm
Successfully installed importlib-resources-5.4.0 tqdm-4.64.1 zipp-3.6.0
```

## missing transformer library
```
python predict_lyso_vs_lytic.py --model_path deeppl_ckpt-340000 --fasta_file phix174_sl.fna 
Creating tmp directory: ./phix174_sl.fna.tmp

python ./run_finetune.py --model_type dna --tokenizer_name=dna6 --model_name_or_path deeppl_ckpt-340000 --task_name dnaprom --do_predict --data_dir ./phix174_sl.fna.tmp --max_seq_length 100 --per_gpu_pred_batch_size=32 --output_dir deeppl_ckpt-340000 --predict_dir ./phix174_sl.fna.tmp --n_process 48
Traceback (most recent call last):
  File "./run_finetune.py", line 37, in <module>
    from transformers import (
ModuleNotFoundError: No module named 'transformers'
Traceback (most recent call last):
  File "predict_lyso_vs_lytic.py", line 71, in <module>
    r = np.load(tmp_dir + "/pred_results.npy")
  File "/home//anaconda3/envs/dnabert/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './phix174_sl.fna.tmp/pred_results.npy'
```

## Install transformer library with pip
```
pip install transformers
Collecting transformers
  Downloading transformers-4.18.0-py3-none-any.whl (4.0 MB)
     |████████████████████████████████| 4.0 MB 1.7 MB/s 
Collecting packaging>=20.0
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 4.3 MB/s 
Collecting huggingface-hub<1.0,>=0.1.0
  Downloading huggingface_hub-0.4.0-py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 4.6 MB/s 
Requirement already satisfied: numpy>=1.17 in /home//anaconda3/envs/dnabert/lib/python3.6/site-packages (from transformers) (1.19.5)
Collecting tokenizers!=0.11.3,<0.13,>=0.11.1
  Downloading tokenizers-0.12.1-cp36-cp36m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (6.6 MB)
     |████████████████████████████████| 6.6 MB 32.2 MB/s 
Requirement already satisfied: dataclasses in /home//anaconda3/envs/dnabert/lib/python3.6/site-packages (from transformers) (0.8)
Collecting requests
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 1.5 MB/s 
Collecting importlib-metadata
  Downloading importlib_metadata-4.8.3-py3-none-any.whl (17 kB)
Collecting filelock
  Downloading filelock-3.4.1-py3-none-any.whl (9.9 kB)
Collecting regex!=2019.12.17
  Downloading regex-2023.8.8-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (759 kB)
     |████████████████████████████████| 759 kB 54.3 MB/s 
Requirement already satisfied: tqdm>=4.27 in /home//anaconda3/envs/dnabert/lib/python3.6/site-packages (from transformers) (4.64.1)
Collecting sacremoses
  Downloading sacremoses-0.0.53.tar.gz (880 kB)
     |████████████████████████████████| 880 kB 121.1 MB/s 
Collecting pyyaml>=5.1
  Downloading PyYAML-6.0.1-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (677 kB)
     |████████████████████████████████| 677 kB 30.5 MB/s 
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home//anaconda3/envs/dnabert/lib/python3.6/site-packages (from huggingface-hub<1.0,>=0.1.0->transformers) (4.1.1)
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.1.4-py3-none-any.whl (104 kB)
     |████████████████████████████████| 104 kB 49.8 MB/s 
Requirement already satisfied: importlib-resources in /home//anaconda3/envs/dnabert/lib/python3.6/site-packages (from tqdm>=4.27->transformers) (5.4.0)
Requirement already satisfied: zipp>=0.5 in /home//anaconda3/envs/dnabert/lib/python3.6/site-packages (from importlib-metadata->transformers) (3.6.0)
Collecting idna<4,>=2.5
  Downloading idna-3.10-py3-none-any.whl (70 kB)
     |████████████████████████████████| 70 kB 4.7 MB/s 
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.20-py2.py3-none-any.whl (144 kB)
     |████████████████████████████████| 144 kB 20.5 MB/s 
Requirement already satisfied: certifi>=2017.4.17 in /home//anaconda3/envs/dnabert/lib/python3.6/site-packages (from requests->transformers) (2021.5.30)
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting click
  Downloading click-8.0.4-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 6.0 MB/s 
Collecting joblib
  Downloading joblib-1.1.1-py2.py3-none-any.whl (309 kB)
     |████████████████████████████████| 309 kB 23.0 MB/s 
Building wheels for collected packages: sacremoses
  Building wheel for sacremoses (setup.py) ... done
  Created wheel for sacremoses: filename=sacremoses-0.0.53-py3-none-any.whl size=895260 sha256=6b8d298bec0862f39bd27ca12531953fac7e0a9b0bf2df85375c58bf9b839450
  Stored in directory: /home//.cache/pip/wheels/4c/64/31/e9900a234b23fb3e9dc565d6114a9d6ff84a72dbdd356502b4
Successfully built sacremoses
Installing collected packages: urllib3, pyparsing, importlib-metadata, idna, charset-normalizer, six, requests, regex, pyyaml, packaging, joblib, filelock, click, tokenizers, sacremoses, huggingface-hub, transformers
Successfully installed charset-normalizer-2.0.12 click-8.0.4 filelock-3.4.1 huggingface-hub-0.4.0 idna-3.10 importlib-metadata-4.8.3 joblib-1.1.1 packaging-21.3 pyparsing-3.1.4 pyyaml-6.0.1 regex-2023.8.8 requests-2.27.1 sacremoses-0.0.53 six-1.16.0 tokenizers-0.12.1 transformers-4.18.0 urllib3-1.26.20
```

# error from DNAbert that I was unable to fix
```
 python predict_lyso_vs_lytic.py --model_path deeppl_ckpt-340000 --fasta_file phix174_sl.fna 
Creating tmp directory: ./phix174_sl.fna.tmp

python ./run_finetune.py --model_type dna --tokenizer_name=dna6 --model_name_or_path deeppl_ckpt-340000 --task_name dnaprom --do_predict --data_dir ./phix174_sl.fna.tmp --max_seq_length 100 --per_gpu_pred_batch_size=32 --output_dir deeppl_ckpt-340000 --predict_dir ./phix174_sl.fna.tmp --n_process 48
Traceback (most recent call last):
  File "./run_finetune.py", line 37, in <module>
    from transformers import (
ImportError: cannot import name 'BertForLongSequenceClassification'
Traceback (most recent call last):
  File "predict_lyso_vs_lytic.py", line 71, in <module>
    r = np.load(tmp_dir + "/pred_results.npy")
  File "/home//anaconda3/envs/dnabert/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './phix174_sl.fna.tmp/pred_results.npy'
```

I was quite excited to try this out. But, I can't spend anymore time debugging this. Please fix the bugs so we can run it and try it. 

many thanks,
Rick

**Comment by Wu-Microbiology** [comment]
Hi Rick,
Thanks for the information! The FileNotFoundError: [Errno 2] No such file or directory:'./**.fna.tmp/pred_results.npy' likely resulted from the DNAbert installation. We have uploaded a deeppl_linux_environment.yml file. Could you please try to reinstall the conda environments and see if it works? We will update the script to predict multiple fasta files shortly.

Thanks,
Yujie
